export const types = {
  SET_CONTACT: 'phoneBook/SET_CONTACT',
  ADD_CONTACT: 'phoneBook/ADD_CONTACT',
  DELETE_CONTACT: 'phoneBook/DELETE_CONTACT',
  UPDATE_CONTACT: 'phoneBook/UPDATE_CONTACT',
  CONTACT_FETCH_START: 'phoneBook/CONTACT_FETCH_START',
  CONTACT_FETCH_FINISHED: 'phoneBook/CONTACT_FETCH_FINISHED',
  CONTACT_FETCH_ERROR: 'phoneBook/CONTACT_FETCH_ERROR',
  CONTACT_FETCH_ERROR_CLEAN: 'phoneBook/CONTACT_FETCH_ERROR_CLEAN',
};